// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Mobius.iOS
{
	public partial class I : UIViewController
	{
		public I (IntPtr handle) : base (handle)
		{
		}
	}
}
